call plug#begin('~/.vim/plugged')
Plug 'yianwillis/vimcdoc'
Plug 'ycm-core/YouCompleteMe'
Plug 'Shougo/echodoc.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'ludovicchabant/vim-gutentags'
Plug 'skywind3000/asynctasks.vim'
Plug 'skywind3000/asyncrun.vim'
Plug 'dense-analysis/ale'
call plug#end()
